"""empty message

Revision ID: abc12c54aac2
Revises: 26d855e04eaa
Create Date: 2021-10-14 11:45:38.668887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abc12c54aac2'
down_revision = '26d855e04eaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('app', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
